[package]
name = "client"
version = "0.1.0"
authors = ["Janito Vaqueiro Ferreira Filho <janito.vff@gmail.com>"]
edition = "2018"

[dependencies]
presentrs = { git = "https://github.com/jvff/presentrs", rev = "270e6f8" }
yew = "0.18"
